force-app/main/default/objects/job_application__c/job_application__c.object-meta.xml
<CustomObject>
    <description>This is to capture and store essential job-related details</description>
    <label>job application</label>
    <nameField>
        <label>job application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>job applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/job_application__c/fields/Follow_up_date__c.field-meta.xml
<CustomField>
    <fullName>Follow_up_date__c</fullName>
    <label>Follow-up date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/job_application__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>Note</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/job_application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Asychronous/JADataCleanUpBatch.cls
public with sharing class JADataCleanUpBatch implements Database.Batchable<SObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator('SELECT Id, Status__c, Follow_Up_Date__c, Note__c FROM Job_Application__c WHERE (Status__c != \'Closed\' AND Status__c != \'Accepted\') AND Follow_Up_Date__c <= :Date.today().addDays(-30)');
    }

    public void execute(Database.BatchableContext BC, list<Job_Application__c> staleApplications){
        List<Job_Application__c> applicationsToUpdate = new List<Job_Application__c>();
        for (Job_Application__c application : staleApplications) {
            application.Status__c = 'Closed';
            application.Note__c = 'Closed by automated process on ' + DateTime.now().format('yyyy-MM-dd HH:mm:ss');
            applicationsToUpdate.add(application);
        }

        if (!applicationsToUpdate.isEmpty()) {
            update applicationsToUpdate;
        }
    }

    public void finish(Database.BatchableContext BC){}
}