force-app/main/default/objects/job_application__c/job_application__c.object-meta.xml
<CustomObject>
    <description>This is to capture and store essential job-related details</description>
    <label>job application</label>
    <nameField>
        <label>job application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>job applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/job_application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/Job_Interview__c.object-meta.xml
<CustomObject>
    <label>Job Interview</label>
    <nameField>
        <displayFormat>JI-{0000}</displayFormat>
        <label>Job Interview</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Type__c.field-meta.xml
<CustomField>
    <fullName>Interview_Type__c</fullName>
    <label>Interview Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-on-One</fullName>
            </value>
            <value>
                <fullName>Panel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Interview__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Interviews</relationshipLabel>
    <relationshipName>Job_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Asychronous/InterviewReminderScheduler.cls
public class InterviewReminderScheduler implements Schedulable {

    public static final String CRON = '0 0 0 * * ?';

    /**
     * Email Notifications: Create a feature that sends an email notification to 
     * the user a day before their scheduled interview.
     */
    public void execute(SchedulableContext sc) {

        Date tomorrow = Date.today().addDays(1);
        List<Job_Interview__c> interviews = [
            SELECT
                Id,
                Interview_Date__c,
                Interview_Type__c,
                Job_Application__c,
                Job_Application__r.Primary_Contact__c
            FROM
                Job_Interview__c
            WHERE
                Interview_Date__c = :tomorrow
        ];


        List<Messaging.SingleEmailMessage> emailMessages = new List<Messaging.SingleEmailMessage>();

        for (Job_Interview__c interview : interviews) {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

            email.setSubject('Interview Reminder');
            email.setHtmlBody('<html><body>This is to remind you of ' + interview.Interview_Type__c + '</body></html>');

            email.setTargetObjectId(interview.Job_Application__r.Primary_Contact__c);
            email.setSaveAsActivity(false);

            emailMessages.add(email);
        }

        Messaging.sendEmail(emailMessages);
    
    }
    
}