force-app/main/default/objects/job_application__c/job_application__c.object-meta.xml
<CustomObject>
    <description>This is to capture and store essential job-related details</description>
    <label>job application</label>
    <nameField>
        <label>job application</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>job applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/job_application__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <label>Primary Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/job_application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Interview__c/Job_Interview__c.object-meta.xml
<CustomObject>
    <label>Job Interview</label>
    <nameField>
        <displayFormat>JI-{0000}</displayFormat>
        <label>Job Interview</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Interviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Date__c.field-meta.xml
<CustomField>
    <fullName>Interview_Date__c</fullName>
    <label>Interview Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Interview__c/fields/Interview_Type__c.field-meta.xml
<CustomField>
    <fullName>Interview_Type__c</fullName>
    <label>Interview Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>One-on-One</fullName>
            </value>
            <value>
                <fullName>Panel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Interview__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Job Interviews</relationshipLabel>
    <relationshipName>Job_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Tests/TestInterviewReminderScheduler.cls
    @isTest
    private class TestInterviewReminderScheduler {

        @TestSetup
        static void setupData(){

        }
    
        @isTest
        static void testInterviewReminderScheduler() {  
            Job_Interview__c testInterview = new Job_Interview__c(
                Interview_Date__c = Date.today().addDays(1),
                Interview_Type__c = 'Panel'
            );
            insert testInterview;

            Job_Application__c testJobApplication = new Job_Application__c(
                Status__c = 'Saved'
            );
            insert testJobApplication;

            testInterview.Job_Application__c = testJobApplication.Id;
            update testInterview;

            Contact testContact = new Contact(
                LastName = 'Test Name', Email = 'test@test.com'
            );
            insert testContact;

            testJobApplication.Primary_Contact__c = testContact.Id;
            update testJobApplication;

            Test.startTest();
            InterviewReminderScheduler scheduler = new InterviewReminderScheduler();
            scheduler.execute(null); 
            Test.stopTest();

            // Assert.areEqual(true, scheduler.wereRemindersSent(), 'Reminders were not sent as expected');

        }
    }
    